// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/language.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_zh_CN Language = 0
	Language_en_US Language = 1
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "zh_CN",
		1: "en_US",
	}
	Language_value = map[string]int32{
		"zh_CN": 0,
		"en_US": 1,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_language_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_proto_language_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_proto_language_proto_rawDescGZIP(), []int{0}
}

var File_proto_language_proto protoreflect.FileDescriptor

var file_proto_language_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6f, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x61,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x20, 0x0a,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x7a, 0x68, 0x5f,
	0x43, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x65, 0x6e, 0x5f, 0x55, 0x53, 0x10, 0x01, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f,
	0x75, 0x79, 0x61, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_language_proto_rawDescOnce sync.Once
	file_proto_language_proto_rawDescData = file_proto_language_proto_rawDesc
)

func file_proto_language_proto_rawDescGZIP() []byte {
	file_proto_language_proto_rawDescOnce.Do(func() {
		file_proto_language_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_language_proto_rawDescData)
	})
	return file_proto_language_proto_rawDescData
}

var file_proto_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_language_proto_goTypes = []interface{}{
	(Language)(0), // 0: io.douya.common.proto.Language
}
var file_proto_language_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_language_proto_init() }
func file_proto_language_proto_init() {
	if File_proto_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_language_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_language_proto_goTypes,
		DependencyIndexes: file_proto_language_proto_depIdxs,
		EnumInfos:         file_proto_language_proto_enumTypes,
	}.Build()
	File_proto_language_proto = out.File
	file_proto_language_proto_rawDesc = nil
	file_proto_language_proto_goTypes = nil
	file_proto_language_proto_depIdxs = nil
}
