// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.3
// source: proto/mail-payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From        string                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nick        string                  `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	To          []string                `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc          []string                `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc         []string                `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject     string                  `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body        string                  `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	ContentType string                  `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Attachment  *MailPayload_Attachment `protobuf:"bytes,9,opt,name=attachment,proto3" json:"attachment,omitempty"`
}

func (x *MailPayload) Reset() {
	*x = MailPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mail_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailPayload) ProtoMessage() {}

func (x *MailPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailPayload.ProtoReflect.Descriptor instead.
func (*MailPayload) Descriptor() ([]byte, []int) {
	return file_proto_mail_payload_proto_rawDescGZIP(), []int{0}
}

func (x *MailPayload) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MailPayload) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *MailPayload) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MailPayload) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *MailPayload) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *MailPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MailPayload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MailPayload) GetAttachment() *MailPayload_Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type MailPayload_Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	WithFile    bool   `protobuf:"varint,3,opt,name=with_file,json=withFile,proto3" json:"with_file,omitempty"`
}

func (x *MailPayload_Attachment) Reset() {
	*x = MailPayload_Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mail_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailPayload_Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailPayload_Attachment) ProtoMessage() {}

func (x *MailPayload_Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailPayload_Attachment.ProtoReflect.Descriptor instead.
func (*MailPayload_Attachment) Descriptor() ([]byte, []int) {
	return file_proto_mail_payload_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MailPayload_Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MailPayload_Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MailPayload_Attachment) GetWithFile() bool {
	if x != nil {
		return x.WithFile
	}
	return false
}

var File_proto_mail_payload_proto protoreflect.FileDescriptor

var file_proto_mail_payload_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6f, 0x2e, 0x64,
	0x6f, 0x75, 0x79, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe9, 0x02, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x63, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x63, 0x63,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x62, 0x63, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4d, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x60, 0x0a, 0x0a, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x79,
	0x61, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mail_payload_proto_rawDescOnce sync.Once
	file_proto_mail_payload_proto_rawDescData = file_proto_mail_payload_proto_rawDesc
)

func file_proto_mail_payload_proto_rawDescGZIP() []byte {
	file_proto_mail_payload_proto_rawDescOnce.Do(func() {
		file_proto_mail_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mail_payload_proto_rawDescData)
	})
	return file_proto_mail_payload_proto_rawDescData
}

var file_proto_mail_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mail_payload_proto_goTypes = []interface{}{
	(*MailPayload)(nil),            // 0: io.douya.common.proto.MailPayload
	(*MailPayload_Attachment)(nil), // 1: io.douya.common.proto.MailPayload.Attachment
}
var file_proto_mail_payload_proto_depIdxs = []int32{
	1, // 0: io.douya.common.proto.MailPayload.attachment:type_name -> io.douya.common.proto.MailPayload.Attachment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mail_payload_proto_init() }
func file_proto_mail_payload_proto_init() {
	if File_proto_mail_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mail_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mail_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailPayload_Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mail_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mail_payload_proto_goTypes,
		DependencyIndexes: file_proto_mail_payload_proto_depIdxs,
		MessageInfos:      file_proto_mail_payload_proto_msgTypes,
	}.Build()
	File_proto_mail_payload_proto = out.File
	file_proto_mail_payload_proto_rawDesc = nil
	file_proto_mail_payload_proto_goTypes = nil
	file_proto_mail_payload_proto_depIdxs = nil
}
