// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/mail-signup-welcome-payload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailSignupWelcomePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To       string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sn       string `protobuf:"bytes,4,opt,name=sn,proto3" json:"sn,omitempty"`
	Ticker   string `protobuf:"bytes,5,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Continue string `protobuf:"bytes,6,opt,name=continue,proto3" json:"continue,omitempty"`
}

func (x *MailSignupWelcomePayload) Reset() {
	*x = MailSignupWelcomePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mail_signup_welcome_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailSignupWelcomePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailSignupWelcomePayload) ProtoMessage() {}

func (x *MailSignupWelcomePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_signup_welcome_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailSignupWelcomePayload.ProtoReflect.Descriptor instead.
func (*MailSignupWelcomePayload) Descriptor() ([]byte, []int) {
	return file_proto_mail_signup_welcome_payload_proto_rawDescGZIP(), []int{0}
}

func (x *MailSignupWelcomePayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MailSignupWelcomePayload) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MailSignupWelcomePayload) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *MailSignupWelcomePayload) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *MailSignupWelcomePayload) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *MailSignupWelcomePayload) GetContinue() string {
	if x != nil {
		return x.Continue
	}
	return ""
}

var File_proto_mail_signup_welcome_payload_proto protoreflect.FileDescriptor

var file_proto_mail_signup_welcome_payload_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x2d, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x2d, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6f, 0x2e, 0x64, 0x6f,
	0x75, 0x79, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa6, 0x01, 0x0a, 0x18, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x73, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x61, 0x2d, 0x69, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mail_signup_welcome_payload_proto_rawDescOnce sync.Once
	file_proto_mail_signup_welcome_payload_proto_rawDescData = file_proto_mail_signup_welcome_payload_proto_rawDesc
)

func file_proto_mail_signup_welcome_payload_proto_rawDescGZIP() []byte {
	file_proto_mail_signup_welcome_payload_proto_rawDescOnce.Do(func() {
		file_proto_mail_signup_welcome_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mail_signup_welcome_payload_proto_rawDescData)
	})
	return file_proto_mail_signup_welcome_payload_proto_rawDescData
}

var file_proto_mail_signup_welcome_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_mail_signup_welcome_payload_proto_goTypes = []interface{}{
	(*MailSignupWelcomePayload)(nil), // 0: io.douya.common.proto.MailSignupWelcomePayload
}
var file_proto_mail_signup_welcome_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mail_signup_welcome_payload_proto_init() }
func file_proto_mail_signup_welcome_payload_proto_init() {
	if File_proto_mail_signup_welcome_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mail_signup_welcome_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailSignupWelcomePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mail_signup_welcome_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mail_signup_welcome_payload_proto_goTypes,
		DependencyIndexes: file_proto_mail_signup_welcome_payload_proto_depIdxs,
		MessageInfos:      file_proto_mail_signup_welcome_payload_proto_msgTypes,
	}.Build()
	File_proto_mail_signup_welcome_payload_proto = out.File
	file_proto_mail_signup_welcome_payload_proto_rawDesc = nil
	file_proto_mail_signup_welcome_payload_proto_goTypes = nil
	file_proto_mail_signup_welcome_payload_proto_depIdxs = nil
}
