// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/system-setting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icp        *string `protobuf:"bytes,1,opt,name=icp,proto3,oneof" json:"icp,omitempty"`
	MainDomain *string `protobuf:"bytes,2,opt,name=main_domain,json=mainDomain,proto3,oneof" json:"main_domain,omitempty"`
	Cdn        *string `protobuf:"bytes,3,opt,name=cdn,proto3,oneof" json:"cdn,omitempty"`
}

func (x *GeneralSetting) Reset() {
	*x = GeneralSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_system_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralSetting) ProtoMessage() {}

func (x *GeneralSetting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralSetting.ProtoReflect.Descriptor instead.
func (*GeneralSetting) Descriptor() ([]byte, []int) {
	return file_proto_system_setting_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralSetting) GetIcp() string {
	if x != nil && x.Icp != nil {
		return *x.Icp
	}
	return ""
}

func (x *GeneralSetting) GetMainDomain() string {
	if x != nil && x.MainDomain != nil {
		return *x.MainDomain
	}
	return ""
}

func (x *GeneralSetting) GetCdn() string {
	if x != nil && x.Cdn != nil {
		return *x.Cdn
	}
	return ""
}

type IdSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeoTitle     *string `protobuf:"bytes,1,opt,name=seo_title,json=seoTitle,proto3,oneof" json:"seo_title,omitempty"`
	SeoKeyword   *string `protobuf:"bytes,2,opt,name=seo_keyword,json=seoKeyword,proto3,oneof" json:"seo_keyword,omitempty"`
	SeoDesc      *string `protobuf:"bytes,3,opt,name=seo_desc,json=seoDesc,proto3,oneof" json:"seo_desc,omitempty"`
	WebSentryDsn *string `protobuf:"bytes,4,opt,name=web_sentry_dsn,json=webSentryDsn,proto3,oneof" json:"web_sentry_dsn,omitempty"`
}

func (x *IdSetting) Reset() {
	*x = IdSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_system_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdSetting) ProtoMessage() {}

func (x *IdSetting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdSetting.ProtoReflect.Descriptor instead.
func (*IdSetting) Descriptor() ([]byte, []int) {
	return file_proto_system_setting_proto_rawDescGZIP(), []int{1}
}

func (x *IdSetting) GetSeoTitle() string {
	if x != nil && x.SeoTitle != nil {
		return *x.SeoTitle
	}
	return ""
}

func (x *IdSetting) GetSeoKeyword() string {
	if x != nil && x.SeoKeyword != nil {
		return *x.SeoKeyword
	}
	return ""
}

func (x *IdSetting) GetSeoDesc() string {
	if x != nil && x.SeoDesc != nil {
		return *x.SeoDesc
	}
	return ""
}

func (x *IdSetting) GetWebSentryDsn() string {
	if x != nil && x.WebSentryDsn != nil {
		return *x.WebSentryDsn
	}
	return ""
}

var File_proto_system_setting_proto protoreflect.FileDescriptor

var file_proto_system_setting_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6f,
	0x2e, 0x64, 0x6f, 0x75, 0x79, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x03, 0x69, 0x63, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x69, 0x63, 0x70, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a,
	0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x64, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x03, 0x63, 0x64, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x69,
	0x63, 0x70, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x63, 0x64, 0x6e, 0x22, 0xdc, 0x01, 0x0a, 0x09, 0x49,
	0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x65, 0x6f, 0x5f,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73,
	0x65, 0x6f, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x73, 0x65,
	0x6f, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x0a, 0x73, 0x65, 0x6f, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x1e, 0x0a, 0x08, 0x73, 0x65, 0x6f, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x73, 0x65, 0x6f, 0x44, 0x65, 0x73, 0x63, 0x88, 0x01, 0x01,
	0x12, 0x29, 0x0a, 0x0e, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x64,
	0x73, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c, 0x77, 0x65, 0x62, 0x53,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x73, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x73, 0x65, 0x6f, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x65,
	0x6f, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65,
	0x6f, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x77, 0x65, 0x62, 0x5f, 0x73,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x64, 0x73, 0x6e, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x61, 0x2d, 0x69, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_system_setting_proto_rawDescOnce sync.Once
	file_proto_system_setting_proto_rawDescData = file_proto_system_setting_proto_rawDesc
)

func file_proto_system_setting_proto_rawDescGZIP() []byte {
	file_proto_system_setting_proto_rawDescOnce.Do(func() {
		file_proto_system_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_system_setting_proto_rawDescData)
	})
	return file_proto_system_setting_proto_rawDescData
}

var file_proto_system_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_system_setting_proto_goTypes = []interface{}{
	(*GeneralSetting)(nil), // 0: io.douya.common.proto.GeneralSetting
	(*IdSetting)(nil),      // 1: io.douya.common.proto.IdSetting
}
var file_proto_system_setting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_system_setting_proto_init() }
func file_proto_system_setting_proto_init() {
	if File_proto_system_setting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_system_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_system_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_system_setting_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_system_setting_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_system_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_system_setting_proto_goTypes,
		DependencyIndexes: file_proto_system_setting_proto_depIdxs,
		MessageInfos:      file_proto_system_setting_proto_msgTypes,
	}.Build()
	File_proto_system_setting_proto = out.File
	file_proto_system_setting_proto_rawDesc = nil
	file_proto_system_setting_proto_goTypes = nil
	file_proto_system_setting_proto_depIdxs = nil
}
